### ISSUE TITLE
eb deploy issue 

### ISSUE THREAD

**Issue by tugan** [awslabs/eb-php-wordpress#1]
Hi 
I'm following step by step instruction and getting the following error during 

wordpress-beanstalk eb deploy                                                                                     
Creating application version archive "app-161115_124930".
Uploading: [##################################################] 100% Done...
INFO: Environment update is starting.                               
ERROR: Service:AmazonCloudFormation, Message:Stack named 'awseb-e-cv58tffqx3-stack' aborted operation. Current state: 'UPDATE_ROLLBACK_IN_PROGRESS'  Reason: null
ERROR: Creating security group named: awseb-e-cv58tffqx3-stack-loadbalancersg-NITQZNUW9FN7 failed Reason: Resource creation cancelled
ERROR: Failed to deploy application.                     

do you have any suggestion?

**Comment by mwunderl** [comment]
Hi tugan,

Check the events for your environment's CloudFormation stack (awseb-e-cv58tffqx3-stack) in the console:
[CloudFormation Stacks](https://console.aws.amazon.com/cloudformation/home?/stacks)

There should be a more detailed error message in one of the events that tells you why the security group creation failed.

Thanks,
-Michael

**Comment by ITmaze** [comment]
I have the same error and the CloudFormation Stack error indicates that the creation of EFS failed because EFS is not available in this region.

**Comment by mwunderl** [comment]
EFS is currently available in [4 regions](http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticfilesystem-region): us-east-1, us-east-2, us-west-2, eu-west-1

**Comment by codevelop-interactive** [comment]
admin/config/system/cron has the cron set to run every 24 hours. Updated this to every 1 hour, in absence of a setting closer to 2 hours.
