### ISSUE TITLE
EFS alternative for regions without EFS?

### ISSUE THREAD

**Issue by hisham** [awslabs/eb-php-wordpress#14]
Why not have an option to use EBS (block storage) if the wordpress server will always be in the same region?

**Comment by mwunderl** [comment]
You would be limited to a single instance, and you would need to do extra work to ensure that you didn't lose everything on instance replacement, redeploy, or platform upgrade. You could get it to work but I don't think it's a strong use case for Elastic Beanstalk.

**Comment by hisham** [comment]
Yeah makes sense. Ended up using S3 instead for media assets and then just git and the eb CLI for the wp plugins / php files with the assumption that anything done on ec2 server is ephemeral. 

Hopefully EFS (or better yet, Lightsail) is added to the Canadian data center soon. In the meantime thank you for your help!
