### ISSUE TITLE
"option_settings" in one of the configuration files failed validation. More details to follow.

### ISSUE THREAD

**Issue by thifranc** [awslabs/eb-php-wordpress#17]
Hi, I'm following this tutorial :  
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-hawordpress-tutorial.html

And I can't get past the "Launch an Elastic Beanstalk Environment"
Each time I create my app I get the following error :  
![screen shot 2017-12-14 at 6 07 33 pm](https://user-images.githubusercontent.com/17310666/34004962-bf9a6568-e0f9-11e7-8945-a885f38c8757.png)

I've tried many times and I'm pretty sure that I'm accurately following the steps, and I can't find out why I keep failling.

I modify my VPC, subnets and IP on the corresponding files from the tutorial.

Do you have any hints/fixes on my mistakes ?

**Comment by mwunderl** [comment]
Hi Thibault,
SubnetC is referenced by the MountTargetC resource in efs-create.config-
[.ebextensions/efs-create.config](https://github.com/awslabs/eb-php-wordpress/blob/42e3a4382c2641e1e0b131a5df99572562e71e7d/.ebextensions/efs-create.config#L35)

Did you remove the SubnetC option (line 15) to only use 2 subnets? If so, you need to remove MountTargetC as well.

**Comment by thifranc** [comment]
Yes that was it !
Thanks a lot, just to be sure, could I leave the default value for subnet or I would have crashed also ?

However, I'm now getting an error still on the build of the beanStalk env :  
![fail2](https://user-images.githubusercontent.com/17310666/34016334-bcccfe4a-e121-11e7-961b-a12d00749dd8.png)

But it doesn't seem to terminate the environment.

But I'm now in trouble at this step :  
```
For EC2 security groups, type a comma after the name of the autogenerated security group followed by the name of the RDS DB instance's security group. It is the name you noted while configuring the security group earlier.
```
I have this error :  
```
Unable to validate settings: Environment named wordpressBeanstalk-env is in an invalid state for this operation. Must be Ready.
```
I don't know why the loadbalancersg couldn't create. I haven't touch any lines of the MountTargetSecurityGroup.

**Comment by SpencerAung** [comment]
@thifranc I was having the same issue. It turns out EFS is not supported in the region I was deploying. You can check if your region is supported [here](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/)

**Comment by thifranc** [comment]
As a matter of fact I've finally changed my setup and do not use beanStalk anymore, and everything works like a charm ! :)  
but thanks anyway for the advice !
