### ISSUE TITLE
Wordpress Autoupdate

### ISSUE THREAD

**Issue by JosephRedfern** [awslabs/eb-php-wordpress#18]
Does Wordpress's Autoupdate functionality have any impact on running Wordpress under EB? Could instances ever get out of sync?

I'm thinking about the scenario when we create a deployment package using WP 4.9.1, this gets deployed and then auto-updated to 4.9.2 -- we then scale to a second instance. Would the second instance be running 4.9.2 (because they're pointed at the same EFS directory), or will there briefly be two versions (with the second instance running 4.9.1 until it auto-updates)?

**Comment by mwunderl** [comment]
Letting WordPress update itself will cause issues with the database. I don't know if there is a way to make that work so we recommend deploying the new version to a different environment and importing your content. See [Updating WordPress](https://github.com/awslabs/eb-php-wordpress#updating-wordpress) in the readme.

**Comment by JosephRedfern** [comment]
Apologies, I do not know how I missed that section of the readme! Thank you for your reply.
