### ISSUE TITLE
Efs

### ISSUE THREAD

**Issue by GeneralCan** [awslabs/eb-php-wordpress#2]
I have a question. And I don't know if this is the place to ask.

Following these directions. Is WordPress set up to run completely from the efs mount or only wp-content/uploads?

**Comment by mwunderl** [comment]
Only wp-content/uploads is stored on the EFS file system. This configuration file creates a simlink to map that folder to the mount folder:
[.ebextensions/efs-mount.config](https://github.com/awslabs/eb-php-wordpress/blob/master/.ebextensions/efs-mount.config)

That leaves your `wp-config.php` file outside of EFS so you can keep it in source control, modify it locally, and deploy changes through Beanstalk.
