### ISSUE TITLE
non-default VPC

### ISSUE THREAD

**Issue by babatundebusari** [awslabs/eb-php-wordpress#3]
#1. Will this work with non-default VPC?
will like to use custom VPC i created

#2. Can i use an already created EFS volume? 
instead of allowing EBS to create one for me?

**Comment by mwunderl** [comment]
Hi babatun,

1- Custom VPC will work as long as you configure your environment to launch instances in the custom VPC. You can use a configuration file like [this one](https://github.com/awslabs/elastic-beanstalk-docs/blob/master/.ebextensions/aws_provided/environment%20configuration/vpc-custom-loadbalanced.config) when you create your environment, use the VPC options on the [eb create command](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-create.html#eb3-createoptions).

2- You can mount an existing file system in the same VPC by removing the efs-create.config file from your the .ebextensions directory and adding the ID of your existing file system to [efs-mount.config](https://github.com/awslabs/eb-php-wordpress/blob/master/.ebextensions/efs-mount.config)
```
option_settings:
  aws:elasticbeanstalk:application:environment:
    EFS_VOLUME_ID: '`{"Ref" : "FileSystem"}`'
``` 
Replace the ref with your file system ID like this:
```
option_settings:
  aws:elasticbeanstalk:application:environment:
    EFS_VOLUME_ID: fs-e7605f4e
```
Thanks,
-Michael

**Comment by babatundebusari** [comment]
@mwunderl 

```
1- Custom VPC will work as long as you configure your environment to launch instances in the custom VPC. **You can use a configuration file like this one when you create your environment**, _use the VPC options on the eb create command_.
```

Is that AND or an OR?
do i need to use that configuration file AND use the VPC options in eb create command or its ither OR?

**Comment by babatundebusari** [comment]
@mwunderl 

never mind
i just used the option available with `eb create ..` and it worked like a champ

**Comment by patricker** [comment]
Found this helpful. URL has moved if someone needs it: https://raw.githubusercontent.com/awslabs/elastic-beanstalk-docs/master/configuration-files/aws-provided/environment-configuration/vpc-custom-loadbalanced.config
