### ISSUE TITLE
using this, will I be able to install plugins in the admin panel of wordpress?

### ISSUE THREAD

**Issue by wobeng** [awslabs/eb-php-wordpress#9]
Hi
using this, will I be able to install plugins in the admin panel of wordpress?

**Comment by Fir3Chi3f** [comment]
eb-php-wordpress shouldn't have an affect on the way Wordpress actually functions. If you're having problems with plugins on a wordpress installation you may have to look elsewhere for help and be a bit more specific about the problem you're having.

**Comment by mwunderl** [comment]
I believe it will work but let me know if you encounter errors.
